# Generated by Django 3.1.3 on 2021-01-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApi', '0009_auto_20210104_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Googleuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=256)),
            ],
        ),
    ]
