# Generated by Django 3.1.3 on 2021-01-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApi', '0010_googleuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleuser',
            name='number',
            field=models.IntegerField(default=1234),
        ),
    ]
