# Generated by Django 3.1.3 on 2021-01-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApi', '0012_auto_20210108_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleuser',
            name='number',
            field=models.CharField(max_length=11),
        ),
    ]
